ucladevx/BQuest-Backend

.github/PULL_REQUEST_TEMPLATE
=> aded pr template

README.md
Adds a better readme that actually has relevant info
I read it
=> [README] Readme update

Makefile, requirements.txt, src/pickmybruin/settings.py, src/users/tests.py, src/users/urls.py, src/users/views.py
Added a few good test examples
ran unit tests
=> [Users] Added tests

Makefile, init_db.sql, initialize.sh
Created a default database that _should_ work for everyone
I deleted the database and restored it
To delete database, 
Inside the postgres container
```psql
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;  // if you don't have this, you will be sad for 30 minutes
```
=> [Database] Set Up Backup and Restore

initialize.sh, src/pickmybruin/settings.py
I removed references to static
make run no longer has errors :P
=> [Settings] Removed references to static

.gitignore, Makefile, init_db.sql
test@marktai.com didn't have a password set.  Now it does.
I logged into test@marktai.com
=> [Database] Updated init_db.sql

initialize.sh, src/pickmybruin/settings.py
Apparently you need the static stuff to have CSS for the admin file
=> Revert "[Settings] Removed references to static"

docker-compose.yml, src/pickmybruin/settings.py
There was a few problems with authentication and `request.user`.  I changed the order of middleware and now it's fixed
I also set `PYTHONUNBUFFERRED=1` in the `docker-compose`.  It was annoying me to not see my print statments.
Got `request.user` and verified it was the same as the token
=> [Settings.py] Fixed authentication

README.md
[##]Description
I added an API section to the README
Looks good
=> [Readme] Added API

README.md
Added screenshots for authorization to the README
Looks pretty
=> [Readme] added screenshots

README.md
=> [README] added make init_db to readme

requirements.txt, src/pickmybruin/settings.py, src/users/factories.py, src/users/tests.py
Factories make testing even easier.  Feel free to look at the code differences.
You can also theoretically use them to create new users really easily, but I don't really use them that way.
Tests pass.
=> [Factories] Set up factories and added them to users

README.md, src/users/serializers.py
User ID was confusing for the front end. It's gone now.
Created a new user and checked the output.
=> [Users] Remove User ID from responses

README.md, src/users/views.py
If ran in development (settings.DEBUG ==True), verification link goes to localhost rather than website
if settings.DEBUG is set to True, the url changes to localhost
=> Send Localhost Link

src/pickmybruin/urls.py, src/users/urls.py
Removed a word so that the url isn't ever users/users
Opened the new URL
=> The Great URL Redesign

README.md, src/email_requests/factories.py, src/email_requests/tests.py, src/email_requests/urls.py, src/email_requests/views.py
This adds the API endpoint to get all the requests made for a specific mentor, and also adds tests for creating and listing requests
GET /requests/list/me
=> Get requests--Alex

README.md, src/email_requests/views.py
Formatted the email for the request.
=> Changed request email format

src/users/tests.py, src/users/views.py
This makes a mentor active if posting to /mentors/me and it already exists
Unit tests.
=> [Mentors] Fix mentor post

src/users/tests.py
Just touches up the code in the tests from the last pull request
Requests tests were breaking on my computer but I think it because of sendgrid
=> Alex fixed last patch

src/email_requests/views.py
Added the use of SendGrid templates, email designed by Wandi.
Sent email to myself by making a request using postman:
Gmail screenshot:
iPhone Mail app screenshot:
**Potential problem**
When an email is forwarded, none of the CSS formatting comes through. Seems like this might not be an issue though as there isn't a large need to forward these emails.
Update: Looks like email forwarding messing up styling is a well-known issue and it all depends on the email server.
=> Added Sendgrid email template use

src/email_requests/views.py, src/pickmybruin/settings.py, src/users/views.py
Added the use of a template for the user verification email
Added a user using postman then got this email
=> Alex  verify template

src/users/tests.py, src/users/views.py
title
Test the verify user endpoint with a wrong endpoint.
=> [Verify] added error code to verify users endpoint

src/users/tests.py, src/users/views.py
We could sign up with a mark@marktai.com@ucla.edu as an email
Unit tests should be good enough
=> [Registration] Removed illegal emails

README.md, src/users/views.py
Modified mentor search field in README
https://github.com/ucladevx/BQuest-Backend/issues/42
N/A
=> README Update

src/email_requests/tests.py, src/email_requests/views.py, src/users/views.py
Check response from sendgrid.
202 is the only valid response
*Note: Was checked by forcing validation error despite valid response(200).
Transaction was atomic
=> Check Sendgrid response

src/email_requests/views.py, src/users/tests.py, src/users/views.py
Saw this issue in the data base (emails are case sensitive); added a lower() to prevent it from happening and also put it in email to keep it uniform.
Also removed regex allowing emails without (g.)
Postman
=> Removed case-sensitivity

src/pickmybruin/settings.py
Made a new sendgrid account with more emails, updated the template IDs to use.
ALSO MUST CHANGE SENDGRID KEY FOR THIS TO WORK
Tested with postman and got the emails:
=> Changed Sendgrid account

README.md, src/users/urls.py, src/users/views.py
New Endpoint that resends Verification link with a get request
Postman
=> Resend Verification LInk

README.md, src/users/tests.py, src/users/urls.py, src/users/views.py
Picks N random active mentors and returns them in a random order ( integrated with search)
make test, Postman
=> Allow getting a random selection of mentors

.gitmodules, Makefile, docker-compose.yml, src/messaging/models.py, src/messaging/views.py
Integrates websockets and websocket pushing on messaging reads and sends
This isn't strictly in the API as it's a separate process.  It's kind of weird to document this one.  I'll figure that out later.
The way the websockets server works is that you can subscribe to a certain channel through
`GET websockets/listen/$CHANNEL_ID` and you can publish to a certain channel through `POST websockets/broadcast/$CHANNEL_ID`.  We will restrict broadcasting to only the server.  
- Look at the postman on the right side
- Look at the top right terminal, with the `wscat -l`
- `wscat` is a utility to listen to a websocket
- After sending the postman request, `wscat` receives a websocket update
=> Messaging websockets

src/messaging/tests.py, src/messaging/views.py
I made a few mistakes
Unit tests
=> [Websockets] Some bugfixes

README.md, src/users/tests.py, src/users/views.py
Allow Searching by Minor and Courses
Minor README Edits
make test && Postman
Search in Course
Search in Minor
=> Add Search Option

README.md, requirements.txt
This addition to readme will give a quick outline of how to profile certain features. Particularly profiling unit test gives insight into the performance of function calls under strain or pressure.
Following directions in the readme will reproduce the desired results
=> Added readme & profiling requirements.txt

src/users/views.py
Changed receiver email address to bquest.ucla@gmail.com
=> changed report email address

README.md, src/users/tests.py, src/users/views.py
1. added filters in searching (name, major, bio)
2. deprecated searching for minor and year
3. testing complete
=> Search algo fix

README.md
Added in three missing backticks so that the code segments and headers are properly displayed now.
=> Fixed a little typo in the ReadMe file

src/users/views.py
The sorting algorithm is implemented  
Profile completion > Similarity to search query
=> Sort Mentor Search Result by Profile Completion
